// MENU_PAGE_URL is loaded from local-config.json, generated by setup.bat.
// Run setup.bat once per machine after cloning.
let MENU_PAGE_URL = null;
const configReady = fetch(chrome.runtime.getURL('local-config.json'))
  .then(r => r.ok ? r.json() : {})
  .then(cfg => { MENU_PAGE_URL = cfg.MENU_PAGE_URL || null; })
  .catch(() => {});

let previousTabId = null;
let previousWindowId = null;

chrome.commands.onCommand.addListener((command) => {
  if (command === "open-menu") {
    openMenu();
  }
});

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'getTabs') {
    const menuTabId = sender.tab?.id;
    const menuWindowId = sender.tab?.windowId;
    chrome.tabs.query({ windowId: menuWindowId }).then(tabs => {
      const filtered = tabs
        .filter(tab => tab.id !== menuTabId)
        .map(tab => ({ id: tab.id, title: tab.title, url: tab.url, favIconUrl: tab.favIconUrl }));
      sendResponse({ tabs: filtered, previousTabId });
    });
    return true; // keep message port open for async response
  }

  if (message.action === 'dismissMenu') {
    (async () => {
      if (previousTabId !== null) {
        await focusTab(previousTabId, previousWindowId);
      }
      if (sender.tab?.id) {
        await chrome.tabs.remove(sender.tab.id);
      }
      if (previousTabId !== null) {
        await focusTab(previousTabId, previousWindowId);
      }
    })();
  }

  if (message.action === 'switchTab') {
    (async () => {
      const targetTabId = message.tabId;
      const targetTab = await chrome.tabs.get(targetTabId);
      await focusTab(targetTabId, targetTab.windowId);
      if (message.closeSource && sender.tab?.id) {
        await chrome.tabs.remove(sender.tab.id);
        await focusTab(targetTabId, targetTab.windowId);
      }
    })();
  }
});

async function focusTab(tabId, windowId) {
  await chrome.tabs.update(tabId, { active: true }).catch(() => {});
  await chrome.windows.update(windowId, { focused: true }).catch(() => {});
}

async function openMenu() {
  await configReady;
  if (!MENU_PAGE_URL) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  const [activeTab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  previousTabId = activeTab?.id ?? null;
  previousWindowId = activeTab?.windowId ?? null;
  chrome.tabs.create({ url: MENU_PAGE_URL });
}
