// MENU_PAGE_URL is loaded from local-config.json, generated by setup.bat.
// Run setup.bat once per machine after cloning.
let MENU_PAGE_URL = null;
const configReady = fetch(chrome.runtime.getURL('local-config.json'))
  .then(r => r.ok ? r.json() : {})
  .then(cfg => { MENU_PAGE_URL = cfg.MENU_PAGE_URL || null; })
  .catch(() => {});

let previousTabId = null;
let previousWindowId = null;

chrome.commands.onCommand.addListener((command) => {
  if (command === 'open-tab-menu') openTabMenu();
  if (command === 'open-window-menu') openWindowMenu();
});

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'getTabs') {
    const menuTabId = sender.tab?.id;
    const menuWindowId = sender.tab?.windowId;
    chrome.tabs.query({ windowId: menuWindowId }).then(tabs => {
      const filtered = tabs
        .filter(tab => tab.id !== menuTabId)
        .map(tab => ({ id: tab.id, title: tab.title, url: tab.url, favIconUrl: tab.favIconUrl }));
      sendResponse({ tabs: filtered, previousTabId });
    });
    return true; // keep message port open for async response
  }

  if (message.action === 'getWindows') {
    const menuWindowId = sender.tab?.windowId;
    chrome.windows.getAll({ populate: true }).then(allWindows => {
      const windows = allWindows.map(win => {
        const activeTab = win.id === menuWindowId
          ? win.tabs.find(t => t.id === previousTabId)
          : win.tabs.find(t => t.active);
        return {
          windowId: win.id,
          tabId: activeTab?.id ?? null,
          title: activeTab?.title ?? null,
          url: activeTab?.url ?? null,
          favIconUrl: activeTab?.favIconUrl ?? null,
          isCurrent: win.id === menuWindowId,
          label: getWindowLabel(win.tabs),
        };
      });
      windows.sort((a, b) => {
        if (a.label && b.label) return a.label.localeCompare(b.label);
        if (a.label) return -1;
        if (b.label) return 1;
        return 0;
      });
      sendResponse({ windows });
    });
    return true; // keep message port open for async response
  }

  if (message.action === 'dismissMenu') {
    closeMenuAndFocus(previousTabId, previousWindowId, sender.tab?.id);
  }

  if (message.action === 'switchTab') {
    (async () => {
      const targetTab = await chrome.tabs.get(message.tabId);
      await closeMenuAndFocus(message.tabId, targetTab.windowId, sender.tab?.id);
    })();
  }
});

async function focusTab(tabId, windowId) {
  await chrome.tabs.update(tabId, { active: true }).catch(() => {});
  await chrome.windows.update(windowId, { focused: true }).catch(() => {});
}

async function closeMenuAndFocus(targetTabId, targetWindowId, menuTabId) {
  if (targetTabId !== null) await focusTab(targetTabId, targetWindowId);
  if (menuTabId) await chrome.tabs.remove(menuTabId);
  if (targetTabId !== null) await focusTab(targetTabId, targetWindowId);
}

function getWindowLabel(tabs) {
  for (const tab of tabs) {
    try {
      const url = new URL(tab.url);
      if (url.pathname.endsWith('echo_title.htm')) {
        const title = url.searchParams.get('title');
        if (title) return `[[${title}]]`;
      }
    } catch {}
  }
  return '';
}

async function openTabMenu() {
  await configReady;
  if (!MENU_PAGE_URL) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  const [activeTab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  previousTabId = activeTab?.id ?? null;
  previousWindowId = activeTab?.windowId ?? null;
  chrome.tabs.create({ url: MENU_PAGE_URL + '?type=tabs' });
}

async function openWindowMenu() {
  await configReady;
  if (!MENU_PAGE_URL) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  const [activeTab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  previousTabId = activeTab?.id ?? null;
  previousWindowId = activeTab?.windowId ?? null;
  chrome.tabs.create({ url: MENU_PAGE_URL + '?type=windows' });
}
